### ISSUE TITLE
Entity's fire status is not synced between the entity and its disguise.

### ISSUE THREAD

**Issue by James103** [NucleoidMC/DisguiseLib#13]
To reproduce:
1. Starting with Minecraft 1.16.5, install Fabric loader and Fabric API.
2. Install `mobdisguises-1.0.0-fabric` and `disguiselib-1.0.2-fabric`.
3. Create a new world with cheats enabled.
4. `/summon minecraft:iron_golem ~ ~ ~ {CustomName: '""', DisguiseLib: {DisguiseType: "minecraft:player", DisguiseAlive: 1b}, UUID: [I;-873554585,-1697035970,-1367762496,1015370517]}` (summons an Iron Golem disguised as a player)
5. `/summon minecraft:iron_golem` (summons an undisguised Iron Golem)
6. Any of the following:
`/give @p flint_and_steel`
`/give @p bow` then hold the bow and `/enchant @p flame`
`/give @p wooden_sword` then hold the sword and `/enchant @p fire_aspect 2`
7. Light both Iron Golems on fire, then observe the resulting behavior:
* The undisguised Iron Golem is properly set on fire.
* The disguised Iron Golem is set on fire server side, but this isn't shown to the client.

**Comment by samolego** [comment]
Should be fixed in 1.0.4
