### ISSUE TITLE
1.17 mixin error

### ISSUE THREAD

**Issue by matthewperiut** [NucleoidMC/DisguiseLib#16]
Attach error for disguiselib.mixins.json:EntityMixin_Disguise during activity: [Transform -> Method disguiseAs(Lnet/minecraft/entity/EntityType;)V -> GETSTATIC -> net/minecraft/class_2703$class_2704::field_12376Lnet/minecraft/class_2703$class_2704;]

This is within my own mod while launching, but my mod is very simple w/o mixins

**Comment by samolego** [comment]
Well, it's not been ported to 1.17 yet, so issues are ro be expected :).
