### ISSUE TITLE
Using disguiseAs crashes 1.17

### ISSUE THREAD

**Issue by matthewperiut** [NucleoidMC/DisguiseLib#17]
I made sure to not use any other mods and to try it in an example-fabric-mod project, but regardless disguiseAs crashes the game. The log is below, further down is my code that I added into fabric-example-mod

(Editted to use pastebin)

// error
https://pastebin.com/zgHRQjYz

// source
https://pastebin.com/uUcHsGhd

// full log
https://pastebin.com/YL85bYPm

**Comment by samolego** [comment]
Thanks for report, could you append logs as well? And please use a paste site :)

**Comment by samolego** [comment]
Oh, and please make sure code is executing in server only (not sure if it is in above example). So ```java
if(!world.isClient)
 ... disguise ...
```

**Comment by matthewperiut** [comment]
Oh wait actually I think I see why
java.lang.NullPointerException: Cannot invoke "net.minecraft.scoreboard.Team.getPlayerList()" because "team" is null
in full log

I wish I saw that haha

**Comment by matthewperiut** [comment]
Oh! world.isClient worked :) You should really add that to the api documentation!
