### ISSUE TITLE
modImplementation failure

### ISSUE THREAD

**Issue by matthewperiut** [NucleoidMC/DisguiseLib#19]
the modImplementations in readme.md don't work in projects, but jitpack did like so:
modImplementation 'com.github.NucleoidMC.DisguiseLib:disguiselib-fabric:1.0.3'

Although, since 1.0.4 (and in future releases) jitpack fails compilation with an older version of java, so this workaround no longer works, and the readme modImplementation also seems to fail.

**Comment by Patbox** [comment]
You should just use nucleoid's maven. The library is there, so not sure why it failed https://maven.nucleoid.xyz/xyz/nucleoid/disguiselib-fabric/1.0.4/

**Comment by samolego** [comment]
If you don't need forge / common version, nucleoid maven is the way to go as Patbox mentioned.
I can implement a fix for jitpack though (I think TheEpicBlock mentioned it).
