### ISSUE TITLE
DisguiseLib 1.2.0 on Minecraft 1.18.1 crashes on startup 

### ISSUE THREAD

**Issue by James103** [NucleoidMC/DisguiseLib#22]
As of DisguiseLib release 1.2.0 (commit 3ba119472e750f3cf09fe9eb9421fa217c787715) and Minecraft 1.18.1, the game crashes on startup with the following error: https://gist.github.com/James103/358cbee1ff9dd081f4f77aebf42b367c

Is there any way that I can run DisguiseLib on Minecraft 1.18.1 without crashing on startup?

**Comment by samolego** [comment]
Thanks for report! Seems like refmap isn't loading.
