### ISSUE TITLE
Resilience against hacked clients on an anarchy server

### ISSUE THREAD

**Issue by LoganDark** [NucleoidMC/DisguiseLib#26]
Hello - as the title states, is this library resilient against hacked clients and other client modifications? Other than the fact that disguises probably won't move naturally for the entity, is there any network information that implies it's a player or not a real entity?

I ask because this doesn't seem to be documented anywhere. If no, it should probably be explicitly documented that the library is visual-only.

**Comment by Patbox** [comment]
Aside from movement, there should be little to no differences most of the time. Only thing noticable would be higher amount of updates for some entities (paintings/etc), through it shouldn't be an issue

**Comment by LoganDark** [comment]
Alright, ty! Closing
