### ISSUE TITLE
Player name in playerlist is not gameprofile's name

### ISSUE THREAD

**Issue by mmm1245** [NucleoidMC/DisguiseLib#3]
When I disguise zombie as player and give that disguise GameProfile with name mmm1245, name in tablist isnt mmm1245, but Zombie

You can probably fix this by replacing this.getName() at line 239 in entitymixin_disguise with this.disguiselib$profile.getName()

**Comment by samolego** [comment]
Thanks for reporting. Should be an easy fix as you've mentioned.
